#! /bin/sh
# /etc/init.d/siahsd
#
# Written by Wilco Baan Hofman <wilco@baanhofman.nl>

### BEGIN INIT INFO
# Provides:          siahsd
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:      postgresql mysql
# Should-Stop:       postgresql mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SIA-HS Daemon
# Description:       SIA-HS Daemon
### END INIT INFO

DAEMON=/usr/local/src/siahsd/build/siahsd
DAEMON_ARGS=
PIDFILE=/var/run/siahsd.pid

start() {
        echo -n "Starting SIA-HS Daemon: "
        if start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS; then
            echo "siahsd."
        else
            echo "FAILED."
            return 1
        fi
}

stop() {
        echo -n "Stopping SIA-HS Daemon: "
        if start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON; then
            echo "siahsd."
        else
            echo "FAILED."
            return 1
        fi
}


case $1 in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        stop
        start
        ;;
esac

